name: catchlog
description: Private tracking app

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  fl_chart: ^1.2.0
  firebase_core: ^4.11.0
  cloud_firestore: ^6.6.0
  http: ^1.6.0
  url_launcher: ^6.3.1
  local_auth: ^2.3.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png